version: '3.8'
services:
  web:
    container_name: 'web'
    build:
      context: .
      args:
        UID: $DOCKER_UID
        GID: $DOCKER_GID
        UNAME: $USER
    tty: true
    working_dir: '/demo/home'
    volumes:
      - .:/demo/home:cached
    ports: 
      - "8080:8080"
    entrypoint: /bin/bash
    depends_on:
      - db
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/test
      - FLYWAY_USER=test
      - FLYWAY_PASSWORD=test
      - FLYWAY_LOCATIONS=filesystem:src/main/resources/db/migration
  db:
    image: postgres:11.14
    container_name: db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - test-data:/var/lib/postgresql/data
volumes:
  test-data: