name: Testing Spring Boot Code On Github Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2 #uses：actionsを使う場合
      - run: docker-compose up --abort-on-container-exit
      - if: success()
        run: echo success
      - if: failure()
        run: echo failure